### Prerequisites
Octave Tutorial 1

# 1. Recap

In Octave Tutorial 1, you learned that Octave allows you to store numerical values in **variables** that you can then use to carry out **computations**. You saw that using Octave offers advantages over using a calcualtor and that you can carry out some fairly intensive processes with relatively short snippets of code.

In this tutorial, you'll learn how you can efficiently store many data values in **arrays**, which allows you to easily access these values from a single variable name.

# 2. Why arrays?

Let's suppose you had a class of 30 first-graders, and you wanted to record each of their heights at the beginning of the semester for a class science project. 

You *could* store this information like so:

``BethInitialHeight = 42
DavidInitialHeight = 45
DominiqueInitialHeight = 46
TanishaIniitalHeight = 43
...``

taking up 30 lines to set up your data. If you wanted to repeat this project next school year, you would presumably need to change all these variable names... Time consuming. It doesn't get much better if you use numbers instead, since you'd still have 30 lines like

``InitialHeight1 = 42
InitialHeight2 = 45
InitialHeight3 = 46
IniitalHeight4 = 43
...``

and you would need to type out each one any time you wanted to calculate an average, create a bar graph, etc.

You would likely find it more convenient to store this data set in an **array**. The following code cell sets up an array of student height data.

In [1]:
% Create an array with the listed elements.
% Note that the ; tells Octave to not show the output of this line.
% Octave still carries it out, though!
StudentHeights = [42,45,46,43,41,48,40,44,47,42,45,43,41,42];

% Display some information.
disp('the whole array is')
disp(StudentHeights)
disp('element 2 is')
disp(StudentHeights(2))
disp('elements 2 through 7 are')
disp(StudentHeights(2:7))


the whole array is
  Columns 1 through 13

    42    45    46    43    41    48    40    44    47    42    45    43    41

  Column 14

    42

element 2 is
    45

elements 2 through 7 are
    45    46    43    41    48    40



# 3. Checkpoint

**Run** the code cell above. Describe the printed output of this cell. What information does each printed line tell you? How does the code tell Octave to produce this output?

<details>
<summary>Click here for an answer.</summary>
The first line shows all the array elements in order. This is what ``StudentHeights`` looks like to the computer.

The second line prints "element 2."

The third line prints a subset of the array, starting at element 2 and going through element 7.

</details>

**Modify** the code cell above to show you elements 3 through 13 of the array.

# 4. How does an array work?

We call the numbers in ``StudentHeights[numbers]`` in the code cell above **array indices**. An array's index can run from 1 (the left-most element) to the number of elements (the right-most element). 

This is useful, for example, in our calculation of $e$ from Octave Tutorial 1, where we were evaluating many terms in a series expansion. We could rewrite our code from Octave Tutorial 1 using arrays as follows:

In [8]:
Terms = [ 1, 1, 1/(2*1), 1/(3*2*1) ]

eEstimate = Terms(1) + Terms(2) + Terms(3) + Terms(4) % Add terms together.



Terms =

    1.0000    1.0000    0.5000    0.1667


eEstimate =

    2.6667



# 5. Checkpoint: You try.

**Add code** to add the next term in the series expansion to the list `Terms` in Line 1. Don't forget to add a comma at the end of the previous term, so Octave knows these are separate elements. Then, **add code** to add your new term (using an array index) to the computation in Line 3. Check that you get the same answer for ``eEstimate`` that you did in Octave Tutorial 1.

<details>
<summary>Click here for an answer.</summary>

```
Terms = [ 1, 1, 1/(2*1), 1/(3*2*1), 1/(4*3*2*1) ]

eEstimate = Terms(1) + Terms(2) + Terms(3) + Terms(4) + Terms(5) % Add terms together.
```

</details>



What advantages do you find working with an array for this computation?

# 6. Functions you might use with an array.

One reason we like to use arrays in Octave is because it includes functions we can carry out on arrays. For example, let's suppose we wanted to calculate the average height of our class of first graders. We could use the ``mean()`` function:

In [9]:
% Create an array with the listed elements.
StudentHeights = [42,45,46,43,41,48,40,44,47,42,45,43,41,42];

% Calculate the average height.
mean(StudentHeights)


ans =

   43.5000



# 7. Checkpoint: You try.

**Add code** to try out the following functions on our array of student heights. Google search "Octave" plus the name of each function to learn about it. What information does the function give you? 

* ``length()``
* ``sum()``
* ``prod()``
* ``std()``
* ``sin()``
* ``exp()``

<details>
<summary>Click here for an answer.</summary>

* ``length()`` = How many elements are the array?
* ``sum()`` = What is the total of all the array elements?
* ``prod()`` = What is the product of all the array elements?
* ``std()`` = What is the standard deviation of all the array elements?
* ``sin()`` = What is the sine of each array element? This produces another array!
* ``exp()`` = What is $e$ to the power of of each array element? This produces another array!

</details>



Which of these functions would be useful in our code for calculating $e$ with a series expansion? (There might be more than one.) Try it/them out!

# 8. Arrays make math very convenient.

I hope you noticed the power of the ``sin()`` and ``exp()`` functions above, in that **Octave will act on all elements** of the array. So, if you wanted to get the square of all integers between 1 and 10, you could do the following:

In [14]:
integers = [1,2,3,4,5,6,7,8,9,10]
integers.^2 % The . tells Octave to raise each element of integers to the power 2.


integers =

     1     2     3     4     5     6     7     8     9    10


ans =

     1     4     9    16    25    36    49    64    81   100



What would you do if you wanted to square **only** the 2nd element of the array ``integers`` and ignore the other elements?

<details>
<summary>Click here for an answer.</summary>

```
intergers(2) = 10 %tells the Octave to change only the second element of the array 10  )
intergers(2) = integers(2).^2  %tells the Octave to raise to the power of 2 only the second term in the array)
```

</details>



There are even more tricks with arrays that can make your mathematical work convenient. For example, instead of manually typing all the integers in the code cell above, I could use ``linspace``. What does ``linspace`` do for us in the code cell below? (Google search ``Octave linspace`` to learn more.) How is this more efficient?

In [17]:
integers = linspace(1,10,10)
integers.^2 % The . tells Octave to raise each element of integers to the power 2.


integers =

     1     2     3     4     5     6     7     8     9    10


ans =

     1     4     9    16    25    36    49    64    81   100



We'll use these conveniences with our $e$ code later once we've learned about loops. Arrays with loops are one of the most powerful combinations in Octave.

# 9. Checkpoint

Why is it advantageous for Octave to act on all elements of an array at once?

How might you write a code that changes **only one** element of an array? (Hint: Think back to array indices.) Try out your proposed method in the code cell above to change the left-most element of ``integers`` to a value of 0.

<details>
<summary>Click here for an answer.</summary>

Suppose you defined an array ``myArray``. You could change one element using something like:

```
myArray(3) = aNewValue
```

</details>



# 10. Common errors to watch for.

The most common error people run into with arrays is **asking Octave for an index that isn't there**. Where does this error occur in the code cell below? How can you tell?

<details>
<summary>Click here for an answer.</summary>

In Line 8, we attempt to access an element 62 that doesn't exist.

</details>



In [19]:
ArrayA = linspace(0,1,100)
ArrayB = linspace(1,2,50)

ArrayA(1) = ArrayA(1) + ArrayB(1)

ArrayA(30) = ArrayB(31)^2

ArrayA(60) = ArrayB(62) / ArrayB(10)


ArrayA =

  Columns 1 through 7

         0    0.0101    0.0202    0.0303    0.0404    0.0505    0.0606

  Columns 8 through 14

    0.0707    0.0808    0.0909    0.1010    0.1111    0.1212    0.1313

  Columns 15 through 21

    0.1414    0.1515    0.1616    0.1717    0.1818    0.1919    0.2020

  Columns 22 through 28

    0.2121    0.2222    0.2323    0.2424    0.2525    0.2626    0.2727

  Columns 29 through 35

    0.2828    0.2929    0.3030    0.3131    0.3232    0.3333    0.3434

  Columns 36 through 42

    0.3535    0.3636    0.3737    0.3838    0.3939    0.4040    0.4141

  Columns 43 through 49

    0.4242    0.4343    0.4444    0.4545    0.4646    0.4747    0.4848

  Columns 50 through 56

    0.4949    0.5051    0.5152    0.5253    0.5354    0.5455    0.5556

  Columns 57 through 63

    0.5657    0.5758    0.5859    0.5960    0.6061    0.6162    0.6263

  Columns 64 through 70

    0.6364    0.6465    0.6566    0.6667    0.6768    0.6869    0.6970

  Columns 71 through 7

Index exceeds array bounds.



# 11. You try.

You previously developed a code cell that would calculate the gravitational potential energy $U$ for two objects separated by a distance $r$. Copy and paste that code below, and make the following changes:

1. Create an array of values for $r$. Use ``np.linspace()`` to create an array with many values; you can choose the range.
2. Create an array of values for $U$ at **each** of those values of $r$. Use the convenient array math that Octave offers.

Describe an example of a project in which these arrays of $r$ and $U$ values might be useful.


In [ ]:
# Paste and modify your code here.